export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const RESET_PRODUCT = "RESET_PRODUCT";
export const APPLY_REDUCTION = "APPLY_REDUCTION";
export const REMOVE_REDUCTION = "REMOVE_REDUCTION";
export const CONFIRM_PAYMENT = "CONFIRM_PAYEMENT";
