//Data action
export const UPDATE_CONNECTION_STATE = "UPDATE_CONNECTION_STATE";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_REDUCTION_LIST = "UPDATE_REDUCTION_LIST";

//Payement action
export const APPLY_REDUCTION = "APPLY_REDUCTION";
export const CONFIRM_PAYMENT = "CONFIRM_PAYEMENT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const REMOVE_REDUCTION = "REMOVE_REDUCTION";
export const RESET_PRODUCT = "RESET_PRODUCT";
export const START_CAISSE = "START_CAISSE";

//Product action
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
